### ISSUE TITLE
social bar horizonal cut off

### ISSUE THREAD

**Issue by jraiskin** [siddhanathan/cv#1]
Thanks for sharing your "implementation" of awesome-cv!

I seem to have a strange problem when compiling locally (doesn't appear to happen on the pdf you provide).
The typing on the "social" bar seem to cut off on the left and on the right (hard to see, but you can see the "o" cutting off on the homepage url). 
Did you experience this problem or know how to solve it?

Example: 

![image](https://cloud.githubusercontent.com/assets/19250758/23339319/1e11396a-fc20-11e6-9df8-741895c29f9f.png)

**Comment by jraiskin** [comment]
It's actually slight cutting off from all sides. This is hard to see nut noticeable when using certain characters (like "j")

**Comment by jraiskin** [comment]
I looked into the original repo, seems like that has been fixed. You might want to take a look at this
[minor changes to header styling](https://github.com/posquit0/Awesome-CV/pull/11/files)

**Comment by siddhanathan** [comment]
Thanks!
